version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: biogenom_nutrition
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Biogenom.Nutrition/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=db;Database=biogenom_nutrition;Username=postgres;Password=password
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always

volumes:
  pgdata: